# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YDxPlUOBT__MyoooZVM1ZxiMd7Ote0Cn
"""

from google.colab import drive
drive.mount('/content/drive')

ls

cd/content/drive/MyDrive/dataset/Day4 Dataset/CNN

ls

pwd

!unzip Animal_Dataset.zip

from tensorflow.keras.preprocessing.image import ImageDataGenerator

test_datagen = ImageDataGenerator(rescale= 1./255)

train_datagen = ImageDataGenerator(rescale= 1./255)

x_train = train_datagen.flow_from_directory(r"/content/drive/MyDrive/dataset/Day4 Dataset/CNN/dataset/Training",target_size= (64,64),class_mode = "categorical",batch_size= 24)

x_test = test_datagen.flow_from_directory(r"/content/drive/MyDrive/dataset/Day4 Dataset/CNN/dataset/Testing",target_size= (64,64),class_mode="categorical",batch_size= 24)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Convolution2D,MaxPooling2D,Flatten,Dense

model = Sequential()

model.add(Convolution2D(32,(3,3),activation = "relu",input_shape = (64,64,3)))

model.add(MaxPooling2D(pool_size = (2,2)))

model.add(Flatten())

model.add(Dense(300, activation='relu'))

model.add(Dense(4, activation = "softmax"))

model.compile(loss = "categorical_crossentropy",metrics=["accuracy"],optimizer='adam')

len(x_train)

model.fit(x_train, epochs=2 ,validation_data=x_test, steps_per_epoch=len(x_train), validation_steps=len(x_test))

model.save("animal1.h5")

"""Testing of the model"""

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np

!unzip Animal_Dataset.zip

img = image.load_img("/content/drive/MyDrive/dataset/Day4 Dataset/CNN/dataset/Training/elephants/2Q__ (2).jpeg",target_size=(64,64))

img

x = image.img_to_array(img)

x

x.ndim

x = np.expand_dims(x,axis = 0)

x.ndim

labels = ["bears" "crows" "elephants" "crows"]